=== clinical-biomarkers/backend-pipeline/api/specs/biomarker/response.schema.json
{
    "$schema": "http://json-schema.org/schema#",
    "type": "object",
    "properties": {
        "biomarker_id": {
            "type": "string"
        },
        "biomarker_canonical_id": {
            "type": "string"
        },
        "biomarker_id_md5": {
            "type": "string"
        },
        "canon_id_md5": {
            "type": "string"
        },
        "biomarker_id_new": {
            "type": "string"
        },
        "condition": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "recommended_name": {
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "string"
                        },
                        "name": {
                            "type": "string"
                        },
                        "description": {
                            "type": "string"
                        },
                        "resource": {
                            "type": "string"
                        },
                        "url": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "description",
                        "id",
                        "name",
                        "resource",
                        "url"
                    ]
                }
            },
            "required": [
                "id",
                "recommended_name"
            ]
        },
        "best_biomarker_role": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "role": {
                        "type": "string"
                    }
                },
                "required": [
                    "role"
                ]
            }
        },
        "biomarker_component": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "assessed_biomarker_entity_id": {
                        "type": "string"
                    },
                    "assessed_biomarker_entity_url": {
                        "type": "string"
                    },
                    "assessed_biomarker_entity": {
                        "type": "object",
                        "properties": {
                            "recommended_name": {
                                "type": "string"
                            },
                            "synonyms": {
                                "type": "array",
                                "items": {
                                    "type": "object",
                                    "properties": {
                                        "synonym": {
                                            "type": "string"
                                        }
                                    },
                                    "required": [
                                        "synonym"
                                    ]
                                }
                            }
                        },
                        "required": [
                            "recommended_name",
                            "synonyms"
                        ]
                    },
                    "assessed_entity_type": {
                        "type": "string"
                    },
                    "biomarker_orig": {
                        "type": "string"
                    },
                    "biomarker": {
                        "type": "string"
                    },
                    "evidence_source": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "id": {
                                    "type": "string"
                                },
                                "database": {
                                    "type": "string"
                                },
                                "url": {
                                    "type": "string"
                                },
                                "evidence_list": {
                                    "type": "array",
                                    "items": {
                                        "type": "object",
                                        "properties": {
                                            "evidence": {
                                                "type": "string"
                                            }
                                        },
                                        "required": [
                                            "evidence"
                                        ]
                                    }
                                },
                                "tags": {
                                    "type": "array",
                                    "items": {
                                        "type": "object",
                                        "properties": {
                                            "tag": {
                                                "type": "string"
                                            }
                                        },
                                        "required": [
                                            "tag"
                                        ]
                                    }
                                }
                            },
                            "required": [
                                "database",
                                "id",
                                "url"
                            ]
                        }
                    },
                    "specimen": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "id": {
                                    "type": "string"
                                },
                                "name": {
                                    "type": "string"
                                },
                                "loinc_code": {
                                    "type": "string"
                                },
                                "name_space": {
                                    "type": "string"
                                },
                                "url": {
                                    "type": "string"
                                },
                                "loince_code_url": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "id",
                                "loinc_code",
                                "loince_code_url",
                                "name",
                                "name_space",
                                "url"
                            ]
                        }
                    }
                },
                "required": [
                    "assessed_biomarker_entity",
                    "assessed_biomarker_entity_id",
                    "assessed_biomarker_entity_url",
                    "assessed_entity_type",
                    "biomarker",
                    "biomarker_orig",
                    "evidence_source",
                    "specimen"
                ]
            }
        },
        "evidence_source": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "string"
                    },
                    "database": {
                        "type": "string"
                    },
                    "url": {
                        "type": "string"
                    },
                    "evidence_list": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "evidence": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "evidence"
                            ]
                        }
                    },
                    "tags": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "tag": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "tag"
                            ]
                        }
                    }
                },
                "required": [
                    "database",
                    "evidence_list",
                    "id",
                    "tags",
                    "url"
                ]
            }
        },
        "crossref": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "string"
                    },
                    "url": {
                        "type": "string"
                    },
                    "database": {
                        "type": "string"
                    }
                },
                "required": [
                    "database",
                    "id",
                    "url"
                ]
            }
        },
        "entity_normal_ranges": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "entity_name": {
                        "type": "string"
                    },
                    "entity_id": {
                        "type": "string"
                    },
                    "source": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "source_name": {
                                    "type": "string"
                                },
                                "lab_term": {
                                    "type": "string"
                                },
                                "ranges": {
                                    "type": "array",
                                    "items": {
                                        "type": "object",
                                        "properties": {
                                            "age_grp": {
                                                "type": "string"
                                            },
                                            "sex": {
                                                "type": "string"
                                            },
                                            "mean_val": {
                                                "type": "number"
                                            },
                                            "median_val": {
                                                "type": "number"
                                            },
                                            "sd_val": {
                                                "type": "number"
                                            },
                                            "min": {
                                                "type": "number"
                                            },
                                            "max": {
                                                "type": "number"
                                            },
                                            "q1": {
                                                "type": "number"
                                            },
                                            "q3": {
                                                "type": "number"
                                            },
                                            "iqr": {
                                                "type": "number"
                                            },
                                            "lower_whisker": {
                                                "type": "number"
                                            },
                                            "upper_whisker": {
                                                "type": "number"
                                            },
                                            "n_val": {
                                                "type": "integer"
                                            },
                                            "units": {
                                                "type": "string"
                                            }
                                        },
                                        "required": [
                                            "age_grp",
                                            "iqr",
                                            "lower_whisker",
                                            "max",
                                            "mean_val",
                                            "median_val",
                                            "min",
                                            "n_val",
                                            "q1",
                                            "q3",
                                            "sd_val",
                                            "sex",
                                            "units",
                                            "upper_whisker"
                                        ]
                                    }
                                }
                            },
                            "required": [
                                "lab_term",
                                "ranges",
                                "source_name"
                            ]
                        }
                    }
                },
                "required": [
                    "entity_id",
                    "entity_name",
                    "source"
                ]
            }
        },
        "source_list": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "citation": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "title": {
                        "type": "string"
                    },
                    "journal": {
                        "type": "string"
                    },
                    "date": {
                        "type": "string"
                    },
                    "authors": {
                        "type": "string"
                    },
                    "reference": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "id": {
                                    "type": "string"
                                },
                                "type": {
                                    "type": "string"
                                },
                                "url": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "id",
                                "type",
                                "url"
                            ]
                        }
                    }
                },
                "required": [
                    "authors",
                    "date",
                    "journal",
                    "reference",
                    "title"
                ]
            }
        }
    },
    "required": [
        "best_biomarker_role",
        "biomarker_canonical_id",
        "biomarker_component",
        "biomarker_id",
        "biomarker_id_md5",
        "biomarker_id_new",
        "canon_id_md5",
        "citation",
        "condition",
        "crossref",
        "entity_normal_ranges",
        "evidence_source",
        "source_list"
    ]
}

=== clinical-biomarkers/backend-pipeline/api/specs/biomarker/response.example.json
{"biomarker_id": "AN6278-5", "biomarker_canonical_id": "AN6278", "biomarker_id_md5": "770a40fee1dc4d15c23cd1e9d062ef57", "canon_id_md5": "88c5021d1628e8725b272ea2355c9433", "biomarker_id_new": "QP5373-2", "condition": {"id": "DOID:0080600", "recommended_name": {"id": "DOID:0080600", "name": "COVID-19", "description": "A Coronavirus infectious disease that is characterized by fever, cough and shortness of breath and that has_material_basis_in Severe acute respiratory syndrome coronavirus 2 (SARS-CoV-2), a subtype of Betacoronavirus pandemicum.", "resource": "Disease Ontology", "url": "http://purl.obolibrary.org/obo/DOID_0080600"}}, "best_biomarker_role": [{"role": "prognostic"}, {"role": "predictive"}], "biomarker_component": [{"assessed_biomarker_entity_id": "UPKB:P05231", "assessed_biomarker_entity_url": "https://www.uniprot.org/uniprotkb/P05231/entry", "assessed_biomarker_entity": {"recommended_name": "Interleukin-6", "synonyms": [{"synonym": "IL-6"}, {"synonym": "Interferon beta-2"}, {"synonym": "IFN-beta-2"}, {"synonym": "CTL differentiation factor"}, {"synonym": "CDF"}, {"synonym": "B-cell stimulatory factor 2"}, {"synonym": "BSF-2"}, {"synonym": "Hybridoma growth factor"}, {"synonym": "interleukin-6 isoform 1 precursor"}, {"synonym": "hybridoma growth factor"}, {"synonym": "interleukin BSF-2"}, {"synonym": "B-cell differentiation factor"}, {"synonym": "CTL differentiation factor"}, {"synonym": "interferon beta-2"}, {"synonym": "B-cell stimulatory factor 2"}]}, "assessed_entity_type": "protein", "biomarker_orig": "increased IL6 level", "biomarker": "Increased level of protein IL6/UPKB:P05231", "evidence_source": [{"id": "BMK_000006", "database": "BiomarkerKB Dataset", "url": "https://data.biomarkerkb.org/BMK_000006"}, {"id": "32479790", "database": "PubMed", "url": "https://pubmed.ncbi.nlm.nih.gov/32479790", "evidence_list": [{"evidence": "IL-6 plays multifaceted roles in regulation of vascular leakage, complement activation, and coagulation pathways, which ultimately causes poor outcomes for acute respiratory distress syndrome, multiple organ dysfunction syndrome, and SARS."}, {"evidence": "Elevated IL-6 is a showing of cytokine storm in patients undergoing CAR-T therapy, requiring early action."}, {"evidence": "Serum IL-6 levels are signs of progression to multiple organ dysfunction in severe SARS-CoV-2 cases."}], "tags": [{"tag": "assessed_biomarker_entity"}, {"tag": "best_biomarker_role"}, {"tag": "biomarker"}, {"tag": "condition"}, {"tag": "specimen"}, {"tag": "assessed_biomarker_entity"}, {"tag": "assessed_biomarker_entity_id"}, {"tag": "best_biomarker_role"}, {"tag": "biomarker"}, {"tag": "condition"}, {"tag": "assessed_biomarker_entity"}, {"tag": "assessed_biomarker_entity_id"}, {"tag": "best_biomarker_role"}, {"tag": "biomarker"}, {"tag": "condition"}, {"tag": "assessed_biomarker_entity"}, {"tag": "assessed_biomarker_entity_id"}, {"tag": "best_biomarker_role"}, {"tag": "biomarker"}, {"tag": "condition"}]}, {"id": "32369209", "database": "PubMed", "url": "https://pubmed.ncbi.nlm.nih.gov/32369209", "evidence_list": [{"evidence": "Low lymphocytes, increased IL-6, CRP, PCT, D dimer, and LDH, these finds were similar to previous studies. The increase of these inflammatory indexes indicates that the infected patients were in inflammatory state, which may be closely related to the inflammatory storm. The increase of the cancer biomarkers in patients with COVID-19, especially in severe and critical patients, suggests that inflammation is closely related to the development of COVID-19."}], "tags": [{"tag": "assessed_biomarker_entity"}, {"tag": "best_biomarker_role"}, {"tag": "biomarker"}, {"tag": "condition"}, {"tag": "specimen"}]}, {"id": "32259560", "database": "PubMed", "url": "https://pubmed.ncbi.nlm.nih.gov/32259560", "evidence_list": [{"evidence": "Serial measurement of circulating IL-6 levels may be important in identifying disease progression among COVID-19-infected patients."}], "tags": [{"tag": "assessed_biomarker_entity"}, {"tag": "best_biomarker_role"}, {"tag": "biomarker"}, {"tag": "condition"}, {"tag": "specimen"}]}, {"id": "32428990", "database": "PubMed", "url": "https://pubmed.ncbi.nlm.nih.gov/32428990", "evidence_list": [{"evidence": "The decrease of IL-6 was closely related to treatment effectiveness, while the increase of IL-6 indicated disease exacerbation. Collectively, the dynamic change of IL-6 level can be used as a marker for disease monitoring in patients with severe COVID-19."}], "tags": [{"tag": "assessed_biomarker_entity"}, {"tag": "best_biomarker_role"}, {"tag": "biomarker"}, {"tag": "condition"}, {"tag": "specimen"}]}, {"id": "32677844", "database": "PubMed", "url": "https://pubmed.ncbi.nlm.nih.gov/32677844", "evidence_list": [{"evidence": "Elevated levels of IL-6, D-dimer, CRP, LDH, and ferritin all had an independent increased risk for the clinical outcomes assessed (ICU admission, invasive ventilatory support and death), which were statistically significant."}], "tags": [{"tag": "assessed_biomarker_entity"}, {"tag": "best_biomarker_role"}, {"tag": "biomarker"}, {"tag": "condition"}, {"tag": "specimen"}]}, {"id": "32438331", "database": "PubMed", "url": "https://pubmed.ncbi.nlm.nih.gov/32438331", "evidence_list": [{"evidence": "A deep network analysis has suggested clinical biomarkers predicting the higher risk of severe COVID-19 infection: Hypertension, elevated serum Alanine aminotransferase, high Interleukin-6, and low Lymphocytes count. In particular, patients with diabetes, but also those with prediabetic state, deserve special attention."}, {"evidence": "Clinical biomarkers for chronic inflammation, in particular Interleukin-6, predict the severity of COVID-19."}], "tags": [{"tag": "assessed_biomarker_entity"}, {"tag": "best_biomarker_role"}, {"tag": "biomarker"}, {"tag": "condition"}, {"tag": "specimen"}]}, {"id": "32475810", "database": "PubMed", "url": "https://pubmed.ncbi.nlm.nih.gov/32475810", "evidence_list": [{"evidence": "C-reactive protein, serum amyloid A, interleukin-6, lactate dehydrogenase, neutrophil-to-lymphocyte ratio, D-dimer, cardiac troponin, and renal biomarkers showed significantly higher levels in patients with severe complications of COVID-19 infection compared to their non-severe counterparts."}, {"evidence": "Since the proportionate rise of IL-6 is correlated with disease severity, this study can prove ground-breaking."}], "tags": [{"tag": "assessed_biomarker_entity"}, {"tag": "best_biomarker_role"}, {"tag": "biomarker"}, {"tag": "condition"}, {"tag": "specimen"}]}, {"id": "32234467", "database": "PubMed", "url": "https://pubmed.ncbi.nlm.nih.gov/32234467", "evidence_list": [{"evidence": "Interleukin-6 (IL-6) plays an important role in cytokine release syndrome. If it is possible to block the signal transduction pathway of IL-6, it is expected to become a new method for the treatment of severe COVID-19 patients."}], "tags": [{"tag": "assessed_biomarker_entity"}, {"tag": "best_biomarker_role"}, {"tag": "biomarker"}, {"tag": "condition"}, {"tag": "specimen"}]}, {"id": "32442528", "database": "PubMed", "url": "https://pubmed.ncbi.nlm.nih.gov/32442528", "evidence_list": [{"evidence": "findings in this study include determining independent associations between biomarkers for inflammation (interleukin-6) and thrombosis (D-dimer) and mortality."}], "tags": [{"tag": "assessed_biomarker_entity"}, {"tag": "best_biomarker_role"}, {"tag": "biomarker"}, {"tag": "condition"}, {"tag": "specimen"}]}, {"id": "32161940", "database": "PubMed", "url": "https://pubmed.ncbi.nlm.nih.gov/32161940", "evidence_list": [{"evidence": "lower lymphocyte counts, higher leukocyte counts and neutrophil-lymphocyte ratio (NLR), lower monocytes, eosinophils, and basophils elevated inflammatory cytokines. T cells significantly decreased, helper T (Th) cells and suppressor T cells were below normal levels naive Th cells increased and memory Th cells decreased. lower levels of regulatory T cells."}], "tags": [{"tag": "assessed_biomarker_entity"}, {"tag": "best_biomarker_role"}, {"tag": "biomarker"}, {"tag": "condition"}, {"tag": "specimen"}]}, {"id": "32425269", "database": "PubMed", "url": "https://pubmed.ncbi.nlm.nih.gov/32425269", "evidence_list": [{"evidence": "The maximal level of IL-6, followed by CRP level, was highly predictive of the need for mechanical ventilation. This suggests the possibility of using IL-6 or CRP level to guide escalation of treatment in patients with COVID-19-related hyperinflammatory syndrome."}], "tags": [{"tag": "assessed_biomarker_entity"}, {"tag": "best_biomarker_role"}, {"tag": "biomarker"}, {"tag": "condition"}, {"tag": "specimen"}]}, {"id": "32385523", "database": "PubMed", "url": "https://pubmed.ncbi.nlm.nih.gov/32385523", "evidence_list": [{"evidence": "Up-regulated IL-6 levels may serve as a potential marker for predicting progression of COVID19 patients."}], "tags": [{"tag": "assessed_biomarker_entity"}, {"tag": "best_biomarker_role"}, {"tag": "biomarker"}, {"tag": "condition"}, {"tag": "specimen"}]}, {"id": "32181911", "database": "PubMed", "url": "https://pubmed.ncbi.nlm.nih.gov/32181911", "evidence_list": [{"evidence": "IL-6 and d-D were closely related to the occurrence of severe COVID-19 in the adult patients, and their combined detection had the highest specificity and sensitivity for early prediction of the severity of COVID-19 patients, which has important clinical value."}], "tags": [{"tag": "assessed_biomarker_entity"}, {"tag": "best_biomarker_role"}, {"tag": "biomarker"}, {"tag": "condition"}, {"tag": "specimen"}]}, {"id": "32344321", "database": "PubMed", "url": "https://pubmed.ncbi.nlm.nih.gov/32344321", "evidence_list": [{"evidence": "The serum levels of IL-6 and CRP can effectively assess disease severity and predict outcome in patients with COVID-19."}], "tags": [{"tag": "assessed_biomarker_entity"}, {"tag": "best_biomarker_role"}, {"tag": "biomarker"}, {"tag": "condition"}, {"tag": "specimen"}]}, {"id": "32286245", "databa
